repeat_rate=35
repeat_delay=200

monrule=HDMI,1,1920,0,WL_OUTPUT_TRANSFORM_NORMAL
monrule=NULL,1,0,0,WL_OUTPUT_TRANSFORM_NORMAL

winrule=width:1000,height:250,title:kitty
winrule=offsetx:0,offsety:300,title:kitty
#winrule=fullscreen:1,title:kitty

exec-once = swaybg -c 444444
#exec = kitty

focuscolor=0xFF0000FF
unfocusedcolor=0x00FF00FF
fullscreencolor=0x00FFFFFF

border_radius=10

tap_to_click=1
tap_and_drag=1
drag_lock=1
natural_scrolling=0
disable_while_typing=1
left_handed=0
middle_button_emulation=0

scroll_method=LIBINPUT_CONFIG_SCROLL_2FG
click_method=LIBINPUT_CONFIG_CLICK_METHOD_BUTTON_AREAS
send_events_mode=LIBINPUT_CONFIG_SEND_EVENTS_ENABLED
accel_profile=LIBINPUT_CONFIG_ACCEL_PROFILE_ADAPTIVE
accel_speed=0.0
button_map=LIBINPUT_CONFIG_TAP_MAP_LRM

bind=ALT,Left,focusdir,left
bind=ALT,Right,focusdir,right
bind=ALT,Up,focusdir,up
bind=ALT,Down,focusdir,down

bind=ALT,r,cfgreload

bind=ALT,n,spawn,kitty
bind=WIN+ALT,b,spawn,rofi    -show
bind=ALT,q,kill
bind=ALT,f,togglefullscreen
bind=ALT,o,exitwm

mousebind=ALT,btn_left,moveresize,cursormove
mousebind=ALT,btn_right,moveresize,cursorresize
